[package]
name = "FoodLoops"
version = "1.0.0"
authors = []

[addresses]
food_loops_addr = "0000000000000000000000000000000000000000000000000000000000000001"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }

[dev-dependencies]
